services:
  household-battery-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy-system-optimizer
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
