name: Test Scheduling Logic

on:
    push:
        branches: [main, dev]
        paths:
        - "household_battery/*.py"
        - "config/**"
        - "tests/test_scheduling_logic.py"

jobs:
    test_scheduling_logic:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version-file: '.python-version'

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install the project for testing
              run: uv sync

            - name: Run tests
              run: |
                source .venv/bin/activate
                pytest tests/test_generate_daily_scenarios.py -v -s